---

- name: Add PHP v5.6 apt repository
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP v5.6 for WP-CLI support
  apt: name={{ item }}
  with_items:
  - php5.6
  - php5.6-gd
  - php5.6-mysql
  - php5.6-mcrypt
  - php5.6-curl
  - php5.6-xml
  - php5.6-bcmath
  - php5.6-zip
  - php-pear
